### ISSUE TITLE
patch.edits is missing from the backend

### ISSUE THREAD

**Issue by josephg** [automerge/automerge-rs#142]
I'm trying to give automerge-rs a crack, and I'm running into this error:

```
TypeError: patch.edits is not iterable
    at updateTextObject (/home/seph/3rdparty/automerge/frontend/apply_patch.js:231:28)
    at interpretPatch (/home/seph/3rdparty/automerge/frontend/apply_patch.js:278:12)
    at getValue (/home/seph/3rdparty/automerge/frontend/apply_patch.js:17:12)
    at applyProperties (/home/seph/3rdparty/automerge/frontend/apply_patch.js:69:24)
    at updateMapObject (/home/seph/3rdparty/automerge/frontend/apply_patch.js:107:3)
    at interpretPatch (/home/seph/3rdparty/automerge/frontend/apply_patch.js:272:12)
    at applyPatchToDoc (/home/seph/3rdparty/automerge/frontend/index.js:148:3)
    at makeChange (/home/seph/3rdparty/automerge/frontend/index.js:105:20)
    at Object.change (/home/seph/3rdparty/automerge/frontend/index.js:251:12)
    at change (/home/seph/3rdparty/automerge/src/automerge.js:34:29)
```

It looks like the patch object returned by `applyLocalChange` is weirdly missing some fields:

![image](https://user-images.githubusercontent.com/47413/119125911-b70db180-ba75-11eb-9e66-d6fe26aa2a59.png)

I'm running my code by compiling the cjs package (using the package.json script) then linking, and running it with this code:

```javascript
const automerge = require('automerge')

const backend = require('automerge-backend-wasm')
automerge.setDefaultBackend(backend)

let state = automerge.from({text: new automerge.Text("")}) // this is as far as it gets, then it crashes
```

**Comment by alexjg** [comment]
This is because automerge JS is using a different patch format to `master` in `automerge-rs`. We're in the process of fixing that in #88 , we have one failing test left to fix which is why we haven't merged it yet. The failing test is due to incorrectly failing to report conflicts within list elements - so unless you're depending on being able to access conflicting values in a list element your code should work against that branch.

**Comment by josephg** [comment]
Awesome - that did the trick. Thanks!
