### ISSUE TITLE
Automerge::range and thus Automerge::values do not support lists

### ISSUE THREAD

**Issue by luleyleo** [automerge/automerge-rs#353]
I ran into an error in my app and reproduced it with the following test:
```rust
#[test]
fn get_list_values() {
    let mut doc = AutoCommit::new();
    let list = doc.put_object(ROOT, "list", ObjType::List).unwrap();

    // insert elements
    doc.insert(&list, 0, "First").unwrap();
    doc.insert(&list, 1, "Second").unwrap();
    doc.insert(&list, 2, "Third").unwrap();

    // list elements
    let elements = doc
        .values(list)
        .map(|(key, _value, _id)| key)
        .collect::<Vec<_>>();

    println!("{:?}", elements);
    assert_eq!(elements.len(), 3);
}
```

Which results in:
```
thread 'get_list_values' panicked at 'found list op in range query', automerge/src/query/range.rs:43:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: <automerge::query::range::Range<R> as core::iter::traits::iterator::Iterator>::next
             at ./src/query/range.rs:43:36
   3: <automerge::values::Values as core::iter::traits::iterator::Iterator>::next
             at ./src/values.rs:22:9
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/adapters/map.rs:103:9
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/spec_from_iter_nested.rs:23:32
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/spec_from_iter.rs:33:9
   7: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/mod.rs:2541:9
   8: core::iter::traits::iterator::Iterator::collect
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/iter/traits/iterator.rs:1745:9
   9: test::get_list_values
             at ./tests/test.rs:1026:20
  10: test::get_list_values::{{closure}}
             at ./tests/test.rs:1016:1
  11: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
```

Am I doing something wrong or is this a bug?

**Comment by luleyleo** [comment]
This appears to be due to fb3b740a57212d09ec7df8ac22a3deced79e8e48 where `Range` was changed to only work with `Map`.

**Comment by luleyleo** [comment]
Was there a reason why this was limited to `Map`?

**Comment by orionz** [comment]
This is a bug for sure - thanks - i'll get a patch out later today

**Comment by orionz** [comment]
Merged the PR
