### ISSUE TITLE
Error: there was a decoding problem: Calculated heads differed from actual heads

### ISSUE THREAD

**Issue by rf-** [automerge/automerge-rs#394]
I somehow managed to create a doc ([attached](https://github.com/automerge/automerge-rs/files/8988451/automerge_data.gz)) that can load with vanilla Automerge but not automerge-js:
```
> Automerge.load(require('fs').readFileSync('automerge_data'))
Error: there was a decoding problem: Calculated heads differed from actual heads
    at module.exports.__wbg_new_55259b13834a484c (/Users/rfitz/src/gridlock/gridlock_app/node_modules/automerge-wasm/nodejs/bindgen.js:1430:15)
    at wasm://wasm/00346bd2:wasm-function[1520]:0xc2972
    at wasm://wasm/00346bd2:wasm-function[206]:0x5a450
    at wasm://wasm/00346bd2:wasm-function[1005]:0xb9165
    at module.exports.loadDoc [as load] (/Users/rfitz/src/gridlock/gridlock_app/node_modules/automerge-wasm/nodejs/bindgen.js:229:14)
    at Object.load (/Users/rfitz/src/gridlock/gridlock_app/node_modules/automerge-js/dist/cjs/index.js:138:42)
```
If I then save the doc with vanilla Automerge, it produces a byte-identical file.

**Comment by alexjg** [comment]
I believe the issue here is that automerge-rs is expecting the document to have a sequence of ULEB128 encoded integers representing the indices of the changes at the head of the document in the set of encoded changes - as specified here: https://alexjg.github.io/automerge-storage-docs/#head-indexes

For some reason the data you've posted doesn't include that. How was it generated?

**Comment by ept** [comment]
There are a few strange things about this file:

1. Like @alexjg pointed out, the headIndexes are missing. The JS implementation [tolerates this](https://github.com/automerge/automerge/blob/main/backend/new.js#L1727-L1739), because IIRC previous versions of Automerge did not include this data. However, I think recent versions of Automerge should always include headIndexes. Did you generate this file using an old version?
2. There is another corruption in the file: operation `1950@4064e3119dea451abd54018b0f46d4ac` has its succs appear in the wrong order: `['4817@263463160b084556a972e473e39746f7', '4768@01435e88c3e24efdbfd16a2a7b5ba08b']` (they should be in ascending order). The JS implementation does not complain about this because it's only noticed during hash graph reconstruction, which the JS implementation defers for performance reasons. If you call `Automerge.getAllChanges()` on the document you get an exception "operation IDs are not in ascending order" for this reason.

I think it's unlikely to be a race condition, but there may be some other bug in Automerge. Can you check you're running the latest release (1.0.1-preview.7) of the JS implementation?

**Comment by ept** [comment]
Could you please tell me exactly which library version you used to generate this file? (Pure-JS or Rust/Wasm implementation of Automerge? Which release/commit hash?) Then we can review the code to see under which circumstances it might have produced this corruption. Ideal would be if you could give us a code example that reproduces the problem, although I realise that might be difficult.

**Comment by ept** [comment]
Okay, since you're not using the pure-JS implementation, this must be a bug in the Rust implementation somewhere. I might need to ask for help from @alexjg :)

**Comment by alexjg** [comment]
I suspect that the problem here is that in `Op::add_succ` we don't sort the successors. I'll get a testcase and a fix for that up this weekend.
