### ISSUE TITLE
Uncaught TypeError: 'ownKeys' on proxy: trap returned duplicate entries

### ISSUE THREAD

**Issue by rf-** [automerge/automerge-rs#395]
This is another case where a doc ([attached](https://github.com/automerge/automerge-rs/files/9006519/automerge_data_2.gz)) triggers an error in automerge-js that doesn't appear to happen in upstream Automerge, although it's a little more work to repro than #394:
```
const Automerge = require('automerge-js');
Automerge.use(require('automerge-wasm'));

const doc = Automerge.load(require('fs').readFileSync('automerge_data_2'));

console.log(Object.entries(doc.versions['70d4809a163446aaa91db8c5795e955e'].grid.cells));

// Uncaught TypeError: 'ownKeys' on proxy: trap returned duplicate entries
//    at Function.entries (<anonymous>)
//    at REPL113:1:39
//    at _change (/Users/rfitz/src/gridlock/gridlock_app/node_modules/automerge-js/dist/cjs/index.js:97:9)
//    at Object.change (/Users/rfitz/src/gridlock/gridlock_app/node_modules/automerge-js/dist/cjs/index.js:62:16)
```

**Comment by rf-** [comment]
Oh sorry, I got a 404 when I submitted this the first time. Closing the dupe.
