### ISSUE TITLE
automerge-c: uncaught panic if string contains a null byte

### ISSUE THREAD

**Issue by ConradIrwin** [automerge/automerge-rs#455]
I used the following typescript to create a doc containing a string with a null byte in it:

```typescript
import * as automerge from '@automerge/automerge' // 2.0.0-beta.4

let doc = automerge.init()

var newDoc = automerge.change(doc, (d: any) => {
  d.oops = 'o\x00ps'
})

let bytes = automerge.save(newDoc)
// => hW9KgzgYCpUAdAEQAlGmcMDRTlKAagbMI3V0owG3hG4vm1xsqt7I1lr4Yc0pMEkeiGUjKJAdUqx8qMyy5AYBAgMCEwIjAkACVgIIFQYhAiMCNAFCAlYCVwSAAQJ/AH8BfwF/AH8Afwd/BG9vcHN/AH8BAX8Bf0ZvAHBzfwAA
```

When I try to load this with automerge-C:

```
result = AMmapGet(doc, AM_ROOT, "oops", nil);
C.AMresultStatus(result) == AM_RESULT_OK;
C.AMerrorMessage(result) == "";
value = AMresultValue(result); // rust panic
```

The backtrace (with RUST_BACKTRACE=full):

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(1, [111, 0, 112, 115])', automerge-c/src/result.rs:189:80
stack backtrace:
   0:        0x10059def4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
   1:        0x10056ccc4 - core::fmt::write::hda8e8eb84b49cbfc
   2:        0x1005a1ea8 - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
   3:        0x1005a271c - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
   4:        0x1005a2344 - std::panicking::begin_panic_handler::{{closure}}::hea9e6c546a23e8ff
   5:        0x1005a22bc - std::sys_common::backtrace::__rust_end_short_backtrace::hd64e012cf32134c6
   6:        0x1005a2288 - _rust_begin_unwind
   7:        0x1005ac598 - core::panicking::panic_fmt::hbfde5533e1c0592e
   8:        0x1005ac750 - core::result::unwrap_failed::h68832e989a8867c1
   9:        0x10053c99c - <T as core::convert::Into<U>>::into::h857facbad1afe04c
  10:        0x1004cd370 - _AMresultValue
```

I was expecting this to fail in a different way (either that the string would be "o" instead of "o\x00ps", or that AMresultStatus() would be AM_RESULT_ERR) because C does not support null bytes in strings.

How should this be handled (in my order of preference)?
* Have automerge-c represent strings using AMbyteSpan or a pointer/length pair, and let implementors deal with it (my preferred option)
* Have automerge-c return an error in this case and ask people to not use null bytes in strings.
* Prevent automerge-js from writing nulls (it's pretty common for applications that nominally support unicode to still not support U+0000; e.g. postgresql)
* Have automerge-c return modified utf-8 or some other hack (https://docs.oracle.com/javase/6/docs/api/java/io/DataInput.html#modified-utf-8)
* Have automerge-c silently return a string representing a prefix of the text... (my least preferred option)

----
(unsurprisingly) A similar error happens in the case of a null in a map key:
```typescript
import * as automerge from '@automerge/automerge'

let doc = automerge.init()

var newDoc = automerge.change(doc, (d: any) => {
  d['o\x00ps'] = 'oops'
})
```
When iterating over the MapItems:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(1, [111, 0, 112, 115])', automerge-c/src/doc/map/item.rs:25:36
stack backtrace:
   0:        0x1043a5fd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1543c132bc4e188c
   1:        0x104374da4 - core::fmt::write::hda8e8eb84b49cbfc
   2:        0x1043a9f88 - std::panicking::default_hook::{{closure}}::hdf06011cb093de6a
   3:        0x1043aa7fc - std::panicking::rust_panic_with_hook::h053d4067a63a6fcb
   4:        0x1043aa424 - std::panicking::begin_panic_handler::{{closure}}::hea9e6c546a23e8ff
   5:        0x1043aa39c - std::sys_common::backtrace::__rust_end_short_backtrace::hd64e012cf32134c6
   6:        0x1043aa368 - _rust_begin_unwind
   7:        0x1043b4678 - core::panicking::panic_fmt::hbfde5533e1c0592e
   8:        0x1043b4830 - core::result::unwrap_failed::h68832e989a8867c1
   9:        0x1042cfd78 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h0ef04a9ab9addf5a
  10:        0x104353fe8 - _AMmapRange
  11:        0x1042ceb4c - __cgo_088393c2ab79_Cfunc_AMmapRange
```

**Comment by jkankiewicz** [comment]
> Have automerge-c represent strings using AMbyteSpan or a pointer/length pair, and let implementors deal with it (my preferred option)

@ConradIrwin, this is the approach I took in PR #457.

**Comment by ConradIrwin** [comment]
This is now fixed, thanks @jkankiewicz / @alexjg
